### PR TITLE
Update transgui.tr

### PR DESCRIPTION
**Pull request by sky-khan**
Fixes for Turkish translation

### CODE REVIEW

**Review by PeterDaveHello — COMMENTED** [review]
@sky-khan thanks for your contribution, do you know if there's any native speaker can help us verify this change? Really appreciate your help!

**Comment by sky-khan** [comment]
> @sky-khan thanks for your contribution, do you know if there's any native speaker can help us verify this change? Really appreciate your help!

I'm a native speaker. I'm Turkish.

**Comment by PeterDaveHello** [comment]
@sky-khan yeah I totally understand, just we usually need a reviewer also a native speaker to help confirm 😄

**Comment by sky-khan** [comment]
Well, sorry I'm a lone wolf. I dont know anybody personally who happens to be on github :/

**Comment by PeterDaveHello** [comment]
@sky-khan okay, no worries, just please help me double confirm the changes, I'll use Claude-2 and GPT-4 to help me review it 😆

**Comment by sky-khan** [comment]
Sure, how can I help?

**Comment by PeterDaveHello** [comment]
@sky-khan nothing but a self review of the pull request / commit 😀 Thanks!

**Review by PeterDaveHello — APPROVED** [review]
Reviewed by GPT-4 & Claude-2

**Comment by sky-khan** [comment]
Thanks. This was my very first PR and I dont have access to GPT4 and I didnt know what to do exactly :)

**Comment by PeterDaveHello** [comment]
@sky-khan oh, I just meant to a self-review from you, that's all ;)

**Pull request merged**
