### PR TITLE
Add Inno Setup Unofficial Korean translation files

### PR DESCRIPTION
**Pull request by bluenlive**
Source:
 - http://www.jrsoftware.org/files/istrans/
 - https://github.com/jrsoftware/issrc/blob/master/Files/Languages/Unofficial/Korean.isl

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Anything I can help here?

**Comment by bluenlive** [comment]
Inno setup accepts only ANSI format language file.
BTW, maybe I can only upload in UTF-8 format.

That's why I closed it...

**Comment by PeterDaveHello** [comment]
@bluenlive maybe simply open an issue for tracking first?

**Comment by bluenlive** [comment]
@PeterDaveHello 
New question...
I forked one from master and added 1 file and edited 1 file.
(added: Korean.isl, edited: setup.iss)

https://github.com/bluenlive/transmisson-remote-gui/commits/master

And, I tried to create pull request.
BTW, github show more difference between them.

https://github.com/transmission-remote-gui/transgui/compare/master...bluenlive:master

Is this Okay?

**Comment by PeterDaveHello** [comment]
@bluenlive looks not

**Comment by bluenlive** [comment]
@PeterDaveHello 
Hmm.. Okay, I'll find another way. Thanks!

**Pull request closed without merging**
