### PR TITLE
English language improvements.

### PR DESCRIPTION
**Pull request by Annihilannic**
[https://github.com/transmission-remote-gui/transgui/issues/1165](url)

### CODE REVIEW

**Comment by leonsoft-kras** [comment]
I'll look later.

**Comment by PeterDaveHello** [comment]
The second commit is totally not related to this topic ...

**Comment by Annihilannic** [comment]
Indeed, but it was a trivial cause of the travis build failure.  Any harm?

**Comment by PeterDaveHello** [comment]
@Annihilannic it can be ignored here as it's not related, it needs another updated.

**Comment by PeterDaveHello** [comment]
@Annihilannic I'll handle it

**Pull request merged**
