### PR TITLE
Deduplicate RequestInfo params. 

### PR DESCRIPTION
**Pull request by Ku33ma**
This is a more correct way to solve the problem described in #1325.
Any duplicate fields are removed.

### CODE REVIEW

**Comment by ambroisie** [comment]
Is there any news regarding this MR?

**Comment by PeterDaveHello** [comment]
Waiting for review from @transmission-remote-gui/development

**Comment by PeterDaveHello** [comment]
Let's see if it works.

**Comment by ambroisie** [comment]
@PeterDaveHello I've been running it with this patch at least since my comment, so I can confirm that it works correctly.

**Comment by PeterDaveHello** [comment]
@ambroisie thanks!

**Comment by ambroisie** [comment]
@elbarbudo your raspberry pi's distribution probably applied this patch downstream, whereas Linux Mint hasn't.

**Pull request merged**
