### PR TITLE
Update Polish translation

### PR DESCRIPTION
**Pull request by NanakiPL**
* fixed incorrect uses of apostrophes
* tweaked wording of some strings for consistency
* couple of missing commas
* added missing translations

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@NanakiPL Thanks, would you like to ask anyone who speaks Polish can help us review this change?

**Comment by NanakiPL** [comment]
@PeterDaveHello No one except previous contributors comes to mind. And they're not on GitHub unfortunately.

**Comment by xavery** [comment]
I'm just a passer-by, but I approve.

**Comment by PeterDaveHello** [comment]
Thank you both @NanakiPL @xavery

**Pull request merged**
