### PR TITLE
Move source files in new src subfolder

### PR DESCRIPTION
**Pull request by Diskutant**
This makes the github page more clean, also the user readable files are more visible now.

I changed and tested the mac build script. I changed but not tested the windows script. The unix script needed to be changed I think. Didn't fully understand it without testing.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please discuss before doing any big changes, this change is not going to be merged.

**Comment by PeterDaveHello** [comment]
We don't need to make the page so clean, many many of them need to be at the root of the repo.

**Comment by Diskutant** [comment]
Where should this be discussed?
Why would those files be needed at the root of the repo?

**Comment by PeterDaveHello** [comment]
@Diskutant You can open a issue to discuss

**Pull request closed without merging**
