### PR TITLE
Update Hungarian translation

### PR DESCRIPTION
**Pull request by Gabrov**
Updated Hungarian translation: two lines realigned according to the template, new strings added.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@Gabrov @mikaeldui guys if you'd like to join the translation team in this project please just let me know :)

**Comment by mikaeldui** [comment]
@PeterDaveHello sure, am checking the repo every week I think.

**Comment by PeterDaveHello** [comment]
@mikaeldui cool! Invited you!

**Comment by Gabrov** [comment]
I also gladly update the Hungarian translation in the future or review others contribution.

**Comment by PeterDaveHello** [comment]
@Gabrov I invited you :)

**Pull request merged**
