### PR TITLE
New Feature: #1043 Implement the Display of Relative Dates/Times (to Now) 

### PR DESCRIPTION
**Pull request by antekgla**
Possibility of show Dates/Times in a Relative Format (to now)

### CODE REVIEW

**Comment by antekgla** [comment]
@PeterDaveHello do you know why Travis CI dont do the checks?

**Comment by PeterDaveHello** [comment]
@antekgla let me check ...

**Comment by PeterDaveHello** [comment]
@antekgla https://www.traviscistatus.com/

**Comment by antekgla** [comment]
@PeterDaveHello  Ok,
I dont know how to do now. I have no clue on Travis.
So if anything is expecting to do in our side (cancelling jobs or something like that) please you do it.

**Comment by PeterDaveHello** [comment]
@antekgla We should wait until they fixed the problems, it's not a normal case, Travis CI is not available right now.

**Comment by antekgla** [comment]
@PeterDaveHello what now? Don´t seens like errors for the code... maybe Travis have troubles...

**Comment by PeterDaveHello** [comment]
@antekgla Let's see the result this time, Travis CI seems to be good now.

**Comment by PeterDaveHello** [comment]
Travis CI is coming back, trying...

**Pull request merged**
