### PR TITLE
Client certificate

### PR DESCRIPTION
**Pull request by metallkopf**
Add support for client certificates on non-windows machines

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@metallkopf would you please also provide the screenshots of this feature? Thanks.

**Comment by metallkopf** [comment]
there are two new fields at the end of the form that are enabled by "use ssl"

new1
new2
edit1
edit2

**Comment by PeterDaveHello** [comment]
@metallkopf thanks!

@leonsoft-kras could you help review the code changes here? Thanks!

**Comment by leonsoft-kras** [comment]
> 
> 
> @metallkopf thanks!
> 
> @leonsoft-kras could you help review the code changes here? Thanks!

ok

**Pull request merged**
