### PR TITLE
Don't use integers in place of booleans in RPC

### PR DESCRIPTION
**Pull request by xavery**
A lot of places in transgui use integers in RPC requests where the daemon expects booleans.

A recent commit in Transmission started actually enforcing this as the JSON parsing implementation has changed.

Originally reported in https://github.com/xavery/transgui/issues/79 and cherry-picked from https://github.com/xavery/transgui/commit/409512f85001d0865dba2a21ce1497b2c60c0d8d.

### CODE REVIEW

**Comment by fredo-47** [comment]
I can confirm that transgui is broken when used with newer transmission-daemon dev-versions, regarding functions "Move torrent data" and "Delete torrent data".

After I built transgui with the file changes suggested above, transgui is able to perform these functions again as expected.

**Comment by PeterDaveHello** [comment]
@fredo-47 Thanks for the contribution. I will take my spare time to review them as soon as possible.

**Comment by killemov** [comment]
A bot wrote:
> It's generally a good practice to add comments explaining the purpose of the code, especially when making changes. Consider adding a comment near this code block explaining the purpose of the condition and what it checks for.

Too bad the bot does not warn against over-commenting, so much comments that important stuff gets lost or comments that state the obvious. Only if requesting the field from the request argument had some unforeseen side-effect, a comment about that would be valid otherwise the code itself is clear enough.

**Review by PeterDaveHello — APPROVED** [review]

**Comment by killemov** [comment]
Can anyone tell me if the used JSON parser can handle truthy and falsy values correctly?

**Comment by xavery** [comment]
> Can anyone tell me if the used JSON parser can handle truthy and falsy values correctly?

It's not that simple to determine because you need to explicitly state the type you're accessing when fetching values from a parsed object. However, when you access `Booleans`, it seems to kind-of-sort-of have the "truthy-falsy" behaviour. Have a look yourself :

```pascal
unit TestCase1;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, fpcunit, testregistry, fpjson, jsonparser;

type

  JsonTruthyFalsy= class(TTestCase)
  published
    procedure BoolAsInteger;
    procedure StringboolAsInteger;
    procedure StringboolAsBool;
    procedure StringAsBool;
    procedure IntegerAsBool;
  end;

implementation

procedure JsonTruthyFalsy.BoolAsInteger;
var
  obj : TJSONObject;
begin
  obj := GetJSON('{"foobar":true}') as TJSONObject;
  AssertEquals(obj.Integers['foobar'], 1);
end;

procedure JsonTruthyFalsy.StringboolAsInteger;
var
  obj : TJSONObject;
begin
  obj := GetJSON('{"foobar":"true"}') as TJSONObject;
  AssertEquals(obj.Integers['foobar'], 1);
end;

procedure JsonTruthyFalsy.StringboolAsBool;
var
  obj : TJSONObject;
begin
  obj := GetJSON('{"foobar":"true"}') as TJSONObject;
  AssertTrue(obj.Booleans['foobar']);
end;

procedure JsonTruthyFalsy.StringAsBool;
var
  obj : TJSONObject;
begin
  obj := GetJSON('{"foobar":"transgui"}') as TJSONObject;
  AssertTrue(obj.Booleans['foobar']);
end;

procedure JsonTruthyFalsy.IntegerAsBool;
var
  obj : TJSONObject;
begin
  obj := GetJSON('{"foobar":1}') as TJSONObject;
  AssertTrue(obj.Booleans['foobar']);
end;

initialization
  RegisterTest(JsonTruthyFalsy);
end.
```

Out of those, `StringboolAsInteger` and `StringAsBool` fail.

This means that `"true"` and `1` are converted to true when using `.Booleans`.

**Comment by killemov** [comment]
Good, this means the original Integer "getter" and comparison to 0 were actually bad programming and that it's fixed even if the actual values in the JSON are 0 or 1.

**Pull request merged**
