### PR TITLE
Update Svenska (Swedish) translation

### PR DESCRIPTION
**Pull request by dobber81**
Corrected spelling.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Hi @dobber81, thanks for your contribution!

Do you know any other GitHub user speak Svenska can help we review this pull request? Sorry that I do not, so I can't confirm the change, it'll be great if we can have another native speaker as a review, thank you again!

**Review by PeterDaveHello — COMMENTED** [review]
Hi @dobber81, thanks for your contribution!

Do you know any other GitHub user speak Svenska can help we review this pull request? Sorry that I do not, so I can't confirm the change, it'll be great if we can have another native speaker as a review, thank you again!

**Comment by dobber81** [comment]
> Hi @dobber81, thanks for your contribution!
> 
> Do you know any other GitHub user speak Svenska can help we review this pull request? Sorry that I do not, so I can't confirm the change, it'll be great if we can have another native speaker as a review, thank you again!

Sure! I'll try to find someone to verify the differance between spoken and written swedish language.

**Comment by davidberglund** [comment]
Hey, I'm a native Swedish speaker and can confirm that @dobber81's PR is correct! :)

**Comment by PeterDaveHello** [comment]
@davidberglund Thank you!

**Pull request merged**
