### PR TITLE
Update Dutch translations (transgui.nl)

### PR DESCRIPTION
**Pull request by Vorror93**
Fixed some incorrect Dutch translations.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Hi @Vorror93,

Thank you for your contribution, I'm sorry that I don't speak Dutch, do you know anyone on GitHub who can help us verify the change? Thanks!

**Comment by Vorror93** [comment]
Hi @PeterDaveHello 

I'm not very active on github, so I wouldn't know anyone. Let's hope someone will pop up eventually.

**Comment by Migelo** [comment]
I asked a Dutch friend of mine and he said the changes make sense. I hope that helps.

**Comment by PeterDaveHello** [comment]
@Migelo Cool, thanks👍

**Pull request merged**
